server:
  port: 7070

spring:
  application:
    name: bookkeeping-server

  datasource:
    url: jdbc:mysql://localhost:3306/jizhangben?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:  ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  # H2 内嵌数据库配置（开发测试用）
#  datasource:
#    url: jdbc:h2:mem:bookkeeping
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 自定义配置
jwt:
  secret: "自己的密钥，实际部署一定要换成足够长的随机字符串"
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000
